services:
  api:
    container_name: api-nest
    build:
      context: .
      dockerfile: ./.docker/DockerFile-nest
    # command: bash -c "npm run start:prod"
    # tty: true
    ports:
      - 3000:${API_PORT}
      - 8080:8080
    env_file: .env
  # nginx:
  #   container_name: nginx
  #   build:
  #     context: .
  #     dockerfile: ./docker/DockerFile-nginx
  #   tty: true
  #   depends_on:
  #     - api
  #   environment:
  #     - NGINX_SERVER_NAME=${NGINX_SERVER_NAME}
  #     - NEST_HOST=${NEST_HOST}
  #     - NEST_PORT=${NEST_PORT}
  #     - NGINX_MAX_BODY=${NGINX_MAX_BODY}
  #   ports:
  #     - 80:80
