version: '3.4'
name: midi-friendly-backend
services:
  api:
    container_name: api-nest
    build:
      context: .
      dockerfile: ./.docker/DockerFile-nest
    ports:
      - 3000:${API_PORT}
      - 8080:8080
    env_file: .env
    restart: always
    volumes:
      - ./redis-volume:/data
    # depends_on:
    #   - db
  
  # db:
  #   image: redis:6.0.12-alpine
  #   command: redis-server --protected-mode no
  #   ports:
  #     - "6379:6379"
  #   hostname: db