FROM node:16-alpine3.15

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN mkdir api²
COPY . ./api
WORKDIR /api

RUN npm install --production

RUN npm run build

# ENTRYPOINT ["tail", "-f", "/dev/null"]
CMD ["npm", "run", "start"]
