FROM node:16-alpine3.15

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

RUN mkdir api²
COPY . ./api
WORKDIR /api

RUN npm install

RUN npm run build

ENTRYPOINT ["tail", "-f", "/dev/null"]
CMD ["docker/run.sh"]
