on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build up-to-date .env config
        uses: appleboy/ssh-action@master
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_KEY_SECRET: ${{ secrets.AWS_KEY_SECRET }}
        with:
          envs: RELEASE_VERSION,DATABASE_URL,GOOGLE_MAPS_API_KEY,REDIS_PORT,REDIS_HOST,AWS_ACCESS_KEY,AWS_KEY_SECRET
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            echo "Building API .env for $RELEASE_VERSION"
            cd ./midi-friendly-api
            git fetch --all --tags
            git checkout $RELEASE_VERSION
            if [ -f .env ]; then
                rm .env
            fi     
            touch .env && echo "
            DATABASE_URL=$DATABASE_URL

            GOOGLE_MAPS_API_KEY=$GOOGLE_MAPS_API_KEY

            API_PORT=3333
            API_URL=http://localhost

            REDIS_PORT=6379
            REDIS_HOST=localhost

            JWT_SECRET=1839DJJQZSZ091203
            JWT_REFRESH_SECRET=94012DJQKZDQ20123
            JWT_TOKEN_EXPIRATION=6h
            JWT_REFRESH_TOKEN_EXPIRATION=1d
            JWT_INVITATION_EXPIRATION=30d
            
            NGINX_SERVER_NAME=api.midifriendly.com
            NEST_HOST=localhost
            NEST_PORT=3000
            NGINX_MAX_BODY=100M

            AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
            AWS_SECRET_ACCESS_KEY=$AWS_KEY_SECRET

            AWS_SES_SOURCE_EMAIL=TASTIA<pro.tastia@gmail.com>
            AWS_SES_REGION=eu-central-1
            AWS_REGION=eu-central-1


            AWS_CLOUDWATCH_API_GROUP_NAME=midi-friendly-api
            AWS_CLOUDWATCH_WORKER_GROUP_NAME=midi-friendly-worker
            AWS_CLOUDWATCH_REGION=eu-central-1

            CLIENT_APP_URL=https://app.midifriendly.com
            ADMIN_APP_URL=https://admin.midifriendly.com
            " >> .env
      - name: Build image & deploy
        uses: appleboy/ssh-action@master
        env:
          RELEASE_VERSION: ${{ env.RELEASE_VERSION }}
        with:
          envs: RELEASE_VERSION
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd ./midi-friendly-api 
            git fetch --all --tags
            git checkout $RELEASE_VERSION
            git pull
            bash ./deploy.sh
